export const TOGGLE_EXPAND_MENU_ITEM = 'TOGGLE_EXPAND_MENU_ITEM'

export const CLOSE_MENU = 'CLOSE_MENU'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const TOGGLE_WITHOUT_ANIMATION = 'TOGGLE_WITHOUT_ANIMATION'

export const SOCKET_ONOPEN = 'SOCKET_ONOPEN'

export const SOCKET_ONCLOSE = 'SOCKET_ONCLOSE'

export const SOCKET_ONERROR = 'SOCKET_ONERROR'

export const SOCKET_ONMESSAGE = 'SOCKET_ONMESSAGE'

export const UPDATE_DATA = 'UPDATE_DATA'

export const OPEN_SOCKET = 'OPEN_SOCKET'

export const SELECT_APP = 'SELECT_APP'

export const SELECT_CLIENT = 'SELECT_CLIENT'

export const CLOSE_SOCKET = 'CLOSE_SOCKET'

export const RESET_COUNT = 'RESET_COUNT'

export const INCREMENT_COUNT = 'INCREMENT_COUNT'
